# Generated by Django 2.2.5 on 2019-09-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20190204_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['pk']},
        ),
    ]
