# Generated by Django 2.2.5 on 2019-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20190925_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='favourite_toy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dog',
            name='favourite_treat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
