# Generated by Django 2.2.8 on 2020-01-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20191205_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdog',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdog',
            name='met_in_person',
            field=models.BooleanField(default=False),
        ),
    ]
