# Generated by Django 2.2.8 on 2020-01-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0007_auto_20200115_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpref',
            name='favourite_toy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpref',
            name='favourite_treat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
